#!/usr/bin/env python3

# ******************************************* #
#                                             #
#    ** Macuyler's Automation Cli (MAC) **    #
# This is a cli tool for automating all the   #
# things I don't want to do!                  #
#                                             #
# ******************************************* #

"""
# Usage
- mac
  - install (Install repos from github)
  - remove  (Remove installed repos)
  - upgrade (Upgrade installed repos)

# Info
repos bin -> ~/.macbin/
"""

import sys

from src.bin import install, remove, upgrade
from src.output import show_usage

COMMANDS = ['install', 'remove', 'upgrade']
SHORT_COMMANDS = list(map(lambda x: x[0], COMMANDS))

CMD_FUNCS = {
    'i': install,
    'r': remove,
    'u': upgrade,
}

def main(cmd, fargs):
    """
    Find and run function specified in arguments.
    """
    cmd = cmd.strip().lower()
    if cmd in COMMANDS or cmd in SHORT_COMMANDS:
        func = CMD_FUNCS[cmd[0]]
        func(fargs)
    else:
        show_usage(COMMANDS)

if __name__ == '__main__':
    args = sys.argv
    if len(args) > 1:
        command = args[1]
        main(command, args[2:])
    else:
        show_usage(COMMANDS)
